export const site = {
  url: "https://mashharuki.github.io/sera-remotion-app/",
  telegram: "https://t.me/seraprotocol",
  telegramLabel: "Open Sera community",
  telegramNote: "Official community. Ask for a team introduction.",
  reviewed: "2026-09-18",
};

export const FPS = 30;
export const scenes = [
  {
    start: 0,
    seconds: 3,
    label: "Meet Sera",
    title: "Different currencies.\nOne Sera.",
    body: "Fund, exchange and use stablecoins from one place.",
    caption: "A recorded walkthrough of the Sera app.",
    screenshot: 3,
    screenLabel: "Your multi-currency wallet",
    language: "English",
    flowStep: null,
    callout: "Fund · Exchange · Use",
  },
  {
    start: 3,
    seconds: 4,
    label: "01 · Deposit",
    title: "Start with\nyour balance.",
    body: "Move USDC from your wallet into the exchange balance.",
    caption: "Recorded example · Deposit amounts are illustrative.",
    screenshot: 6,
    screenLabel: "Deposit to exchange balance",
    language: "English",
    flowStep: 1,
    callout: "70 USDC",
  },
  {
    start: 7,
    seconds: 5,
    label: "02 · Create position",
    title: "Set one amount.\nChoose outcomes.",
    body: "Allocate 50 USDC across USDT and JPYC targets.",
    caption: "Recorded example · Displayed rates are not a current quote.",
    screenshot: 7,
    screenLabel: "Create a multi-currency position",
    language: "English",
    flowStep: 2,
    callout: "USDC → USDT + JPYC",
  },
  {
    start: 12,
    seconds: 4,
    label: "03 · Cashback",
    title: "Shop through Sera.\nTrack cashback.",
    body: "Choose a listed store, then follow rewards through payout.",
    caption: "Availability, rates and payout timing vary by store.",
    screenshot: 8,
    screenLabel: "Browse cashback stores",
    language: "English",
    flowStep: 3,
    callout: "Stores → Track → Cashback",
  },
  {
    start: 16,
    seconds: 4,
    label: "Direct swap",
    title: "Or swap\ndirectly.",
    body: "Choose the stablecoins and amount you want to exchange.",
    caption: "Recorded example · Displayed amounts are not a current quote.",
    screenshot: 0,
    screenLabel: "Choose a pair · USDT → JPYC",
    language: "Japanese",
    flowStep: null,
    callout: "USDT → JPYC",
  },
  {
    start: 20,
    seconds: 4,
    label: "Verify",
    title: "Match off-chain.\nSettle on-chain.",
    body: "Sera matches orders. Ethereum settles trades.",
    caption: "Review transaction status and follow the on-chain record.",
    screenshot: 2,
    screenLabel: "Transaction history",
    language: "Japanese",
    flowStep: null,
    callout: "Ethereum record",
  },
  {
    start: 24,
    seconds: 6,
    label: "Let’s connect",
    title: "Your currencies.\nLet’s connect.",
    body: "Meet Sera on Telegram.",
    caption: "Scan to watch again and start a conversation.",
    screenshot: null,
    screenLabel: "",
    language: "English",
    flowStep: null,
    callout: null,
  },
] as const;
export const DURATION_SECONDS = scenes.reduce(
  (total, scene) => total + scene.seconds,
  0,
);
export const DURATION = DURATION_SECONDS * FPS;
export const sources = [
  { title: "Sera overview & architecture", url: "https://docs.sera.cx/" },
  {
    title: "Current deployment & roadmap",
    url: "https://docs.sera.cx/protocol/swap/",
  },
  { title: "Non-custodial design", url: "https://docs.sera.cx/non-custodial/" },
  { title: "Official contact", url: "https://docs.sera.cx/faq/" },
  { title: "Sera brand kit", url: "https://www.sera.cx/brand" },
  {
    title: "BIS: stablecoins in cross-border payments",
    url: "https://www.bis.org/cpmi/publ/d220.pdf",
  },
];
